### ISSUE TITLE
Publish to GitHub Pages

### ISSUE THREAD

**Issue by fpindej** [sde-sw/blazor-interview-app#6]
GitHub pages may be a nice addition to this project once it's production ready 🌮

**Comment by PlesnikJakub** [comment]
It will be fine for the frontend side of things but API would still require some additional servers right? 🤔

**Comment by petrspelos** [comment]
Yes, @PlesnikJakub, Blazor could be hosted statically, but we'd need a server for ASP.NET.

if you can get us a server, I'm able to write the deploy automation. ☺️ I just did that for my website recently.

**Comment by petrspelos** [comment]
Deployments are now automated to @fpindej's server. Closing. ☺️
